name: USD Daily
on:
  schedule:
    - cron: '00 12 * * *' # Runs every day at 12:00 UTC (8:00 VET)
  workflow_dispatch:  # Allows manual triggering

jobs:
  extrayendo_dato:
    permissions:
      contents: write

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: descargar data
        run: |
          FECHA=$(date +"%Y-%m-%d")
          PRECIO=$(curl -k -s "https://bcv.org.ve" | grep -10 "USD" | grep "000" | sed 's|strong>|\n|g'  | grep "</" | grep -v div | sed 's|</|VES|g')
          echo "$FECHA,$PRECIO" > price-now.csv
          if [ ! -s price-now.csv ]; then
            echo "Downloaded CSV file is empty"
            exit 1
          fi

      - name: crear tabla cumulativa
        run: |
          cat price-now.csv >> prices-USD.csv

      - name: Commit results
        if: always()
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git diff --quiet || git stash
          git pull --rebase origin main
          git stash list | grep "stash@{0}" && git stash apply
          git add prices-USD.csv
          git diff --cached --exit-code || git commit -m "tablas actualizada" --allow-empty
          git push --force-with-lease origin HEAD:main

      - name: Insertar Supabase
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          PRECIO: ${{ env.PRECIO }}
          FECHA: ${{ env.FECHA }}
        run: |
          curl -s "${SUPABASE_URL}/rest/v1/coin" \
          -H "apikey: ${SUPABASE_KEY}" \
          -H "Authorization: Bearer ${SUPABASE_KEY}" \
          -H "Content-Type: application/json" \
          -d "{\"name\":\"USD\",\"value\":${PRECIO},\"updated_at\":${FECHA}}" || exit 1

