name: Fetch USD price

on:
  schedule:
    - cron: '00 12 * * *' # Runs every day at 12:00 UTC (8:00 VET)
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_PROJECT_ID: ${{ secrets.PROJECT_ID }}

    steps:
      - uses: actions/checkout@v3

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - run: supabase functions deploy fetch-bcv-rate --project-ref $SUPABASE_PROJECT_ID